services:
  - type: web
    name: transcription-app
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: AZURE_OPENAI_API_ENDPOINT_US2
        sync: false
      - key: AZURE_OPENAI_API_KEY_US2
        sync: false
      - key: AUTHORIZED_EMAIL
        value: sergeyly@gmail.com
      - key: APP_DOMAIN
        value: fouro-audio-streamlit.onrender.com