[server]
headless = true
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
port = 8501
baseUrlPath = ""

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#4285f4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"

[global]
developmentMode = false

[logger]
level = "info"